### ISSUE TITLE
is-referenced-by-count and citedby-count differ

### ISSUE THREAD

**Issue by geometrikal** [CrossRef/rest-api-doc#211]
is-referenced-by-count and citedby-count differ between json and xml

e.g. compare

- http://api.crossref.org/works/10.1111/ecog.02230
- http://api.crossref.org/works/10.1111/ecog.02230/transform/application/vnd.crossref.unixsd+xml

**Comment by kmeddings** [comment]
Hi - yes, we need to update the JSON and will be working on it this week.

**Comment by moqri** [comment]
It seems the issue citation count in JSON is fixed for some of the journals but not for all of them. Is there anyway to find out which one is fixed and which one is not yet?

**Comment by kmeddings** [comment]
Do you have an example of one that is still showing different counts?

**Comment by moqri** [comment]
I'll check the data and will post here if they are still different. 

Meanwhile you might find this interesting: 
the following article has the referenced-by-count of zero while it is cited more than 70 times and lots of them from Elsevier

http://api.crossref.org/works/http://dx.doi.org/10.13040/IJPSR.0975-8232.1(1).29-46

* the cited-by for this specific article is also 0 by the way

**Comment by kmeddings** [comment]
Hi - that DOI is for a journal issue. Looking at some of the other DOIs from the same journal though it's all a bit confused - the latest issue's DOIs aren't registered at all. Looks like they are getting some sort of data from Google Scholar. Very few of their DOIs resolve properly.
